### ISSUE TITLE
Issue setting both `excludeInternal` and `placeInternalsInOwningModule`

### ISSUE THREAD

**Issue by HarelM** [Gerrit0/typedoc-plugin-missing-exports#23]
**Bug report**

When setting both `excludeInternal` and `placeInternalsInOwningModule` I get the following warning:
[warning] [typedoc-plugin-missing-exports] Both placeInternalsInOwningModule and internalModule are set, the internalModule option will be ignored.

**Input code**

This is the branch I'm working on:
https://github.com/maplibre/maplibre-gl-js/tree/ff7591df40bca0ac68a8c515dc84b0b281c54231

Let me know if this is enough in order to understand the issue.

**Expected output**

No warnings

**Actual output**

See above warnings

**Additional context**
Let me know if you need more info.

**Comment by Gerrit0** [comment]
I'm pretty sure you are mixing up two options.

- `internalModule` - typedoc-plugin-missing-exports option to define the name of the module created for internals
- `excludeInternal` - typedoc option to remove reflections marked with `@internal`

You are getting this warning because of the first of these. This plugin doesn't have any references to `excludeInternal`.

It doesn't make sense to set both `internalModule` and `placeInternalsInOwningModule` because the `placeInternalsInOwningModule` option disables creating the module whose name is defined by `internalModule`.

https://github.com/Gerrit0/typedoc-plugin-missing-exports/blob/4c1b70c38c686e797fcd564e5355bcea0d29a58c/index.ts#L94-L101

**Comment by HarelM** [comment]
Yes, I don't know, I must have been playing around with all the configurations too much.
The warning is clear and makes sense.
Sorry...
